version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD=root
          # - MYSQL_DATABASE=booking
          # - MYSQL_USER=root
          # - MYSQL_PASSWORD= root
    executor:
      name: node/default
      tag: '12.16.3'
    steps:
      - checkout
      - run: sudo apt update 
      - run: sudo apt-get install mysql-client
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run mysql
      - run: npm run db:setup
      - run: npm run test
